apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: xwiki-netpol
spec:
  ingress: 
    -
      from: 
        -
          podSelector:
            matchLabels:
              app: xwiki-label
      ports:
        -
          port: 8080
          protocol: TCP
  podSelector: 
    matchLabels:
      app: xwiki-label
  policyTypes:
    - Ingress
