apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits: 
      storage: 1Gi
    requests: 
      storage: 1Gi
# The storageClass would change if not running on openshift.
  storageClassName: gp2
